module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    letterSpacing: {
      tighter: "-0.05em",
      wide: "0.025em",
      wider: "0.05em",
      widest: ".25em",
    },
    borderWidth: {
      DEFAULT: "1px",
      0: "0",
      2: "2px",
      3: "3px",
      4: "4px",
      6: "6px",
      8: "8px",
    },
    lineHeight: {
      4: "1rem",
      12: "3.5rem",
      10: "2.5rem",
      7: "1.75rem",
      lhxl: "2.4rem",
      lhlg: "2rem",
      lh2xl: "3rem",
    },
    fontSize: {
      xs: ".75rem",
      sm: ".875rem",
      tiny: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
      heading2: "3.5rem",
      heading1: "3.2rem",
    },
    fontFamily: {
      body: [
        "Gotham A",
        "Gotham B",
        "Helvetica",
        "Roboto",
        "Arial",
        " sans-serif",
      ],
      times: [
        "freight-big-pro",
        "Bookman",
        "Times New Roman",
        "Times",
        "serif",
      ],
    },
    extend: {
      backgroundImage: {
        uptown: "url('../src/assets/images/bg-img1.jpg')",
        uptownConstruction:
          "url('../src/assets/images/News-Uptown_Construction.png')",
        contactUs: "url('../src/assets/images/please-use-page-8-8.png')",
        locations:
          "url('../src/assets/images/One-provided-wasnt-as-sharp-and-was-less-vibrant.png')",
        creators: "url('../src/assets/images/IMAGE-darken-2.png')",
        bitmap: "url('../src/assets/images/bitmap.jpg')",
        mapResize: "url('../src/assets/images/map_resize.jpg')",
        almasTower: "url('../src/assets/images/Almas_Tower_entrance.jpg')",
        architects: "url('../src/assets/images/architects.png')",
        partner: "url('../src/assets/images/partner.jpg')",
        uptwonTower:
          "url('../src/assets/images/UPTOWN_TOWER_HERO_darken-1.png')",
        business: "url('../src/assets/images/business.png')",
        dubaiResidence: "url('../src/assets/images/dubaiResidence.jpg')",
        dubaiHotel: "url('../src/assets/images/dubaiHotel.png')",
        SOStyle: "url('../src/assets/images/SOStyle.jpg')",
        officeLeasing: "url('../src/assets/images/officeLeasing.jpg')",
      },
      colors: {
        lightBlack: "rgba(0, 0, 0, .4)",
        galaxy: "#613c36",
        navyBlue: "#130F44",
        lightGrey: "#F5F5F5",
      },
    },
  },
  plugins: [],
};
